server:
  port: 3020

spring:
  application:
    name: slack-service
  config:
    import: 'optional:configserver: '
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  ai:
    vertex.ai.gemini:
      projectId: gen-lang-client-0988494419
      location: us-west1


eureka:
  instance:
    prefer-ip-address: false
    hostname: 35.216.57.113

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://35.216.57.113:3150/eureka/

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace